language: ruby
rvm:
  - 2.1.0
env:
  - RAILS_ENV=test
before_script:
  - "mysql -e 'create database my_app_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
before_install:
  pip install codecov
after_success:
  codecov
